route:
  receiver: webhook-default
  group_by: ["alertname"]
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: webhook-default
    webhook_configs:
      - url: http://webhook:8080/
        send_resolved: true
